name: Testing
on:
  push:
    branches:
      - master
  release:
    types: [created]
jobs:
  versionjob:
    runs-on: macOS-latest
    steps:
      - name: data as version
        run: |
         echo "::set-output name=VERSION::$(date +'%Y.%-m.%-d')"
         echo "::set-output name=LATEST_TAG_NUMBER::$(git describe --tags `git rev-list --tags --max-count=1`)"
        id: dateversion
    outputs:
     if: github.event_name == 'push'
     versiontext: ${{ steps.dateversion.outputs.VERSION }}
     if: github.event_name == 'release'
     versiontext: ${{ steps.dateversion.outputs.LATEST_TAG_NUMBER }}
  version-update:
    if: github.event_name == 'push'
    name: Version increment
    runs-on: macOS-latest
    needs: [versionjob]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: Get commits count
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count HEAD)"
        id: commits
      - name: update version
        run: |
          echo "::set-output name=VERSION::$(date -j -v +1d -f "%Y.%m.%d" "${{steps.dateversion.outputs.LATEST_TAG_NUMBER}}" +'%Y.%-m.%-d')"
        id: updatedversion
      - name: Set version and build number
        run: |
          echo "version=${{needs.versionjob.outputs.versiontext}}"
